keyconfig_version = (3, 6, 14)
keyconfig_data = \
[("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("sna.seltovertcol_operation", {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.move_along_view", {"type": 'Y', "value": 'PRESS', "alt": True}, None),
    ("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'W', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'MOUSESMARTZOOM', "value": 'ANY'}, None),
    ("view3d.localview_remove_from", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.localview_remove_from", {"type": 'SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'NORTH'},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'SOUTH'},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'EAST'},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'WEST'},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CW', "value": 'PRESS'},
     {"properties":
      [("angle", 1.5707964),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("angle", -1.5707964),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ],
   },
  ),
 ("File Browser Main",
  {"space_type": 'FILE_BROWSER', "region_type": 'WINDOW'},
  {"items":
   [("poselib.apply_pose_asset", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("open", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("file.mouse_execute", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ("deselect_all", True),
       ],
      },
     ),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", True),
       ("open", False),
       ],
      },
     ),
    ("file.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("fill", True),
       ("open", False),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ],
      },
     ),
    ("file.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("extend", True),
       ("fill", True),
       ],
      },
     ),
    ("file.previous", {"type": 'BUTTON4MOUSE', "value": 'CLICK'}, None),
    ("file.next", {"type": 'BUTTON5MOUSE', "value": 'CLICK'}, None),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("file.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("file.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("file.select_box", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("file.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("file.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("file.highlight", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("file.sort_column_ui_context", {"type": 'LEFTMOUSE', "value": 'PRESS', "any": True}, None),
    ("file.view_selected", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'ASSETBROWSER_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'ASSETBROWSER_MT_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Graph Editor",
  {"space_type": 'GRAPH_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.context_toggle",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_handles'),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("column", True),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("column", True),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("curves", True),
       ],
      },
     ),
    ("graph.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ("curves", True),
       ],
      },
     ),
    ("graph.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("graph.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("graph.select_leftright",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'LEFT'),
       ],
      },
     ),
    ("graph.select_leftright",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'RIGHT'),
       ],
      },
     ),
    ("graph.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("graph.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("graph.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("graph.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("graph.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("graph.select_box",
     {"type": 'B', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis_range", True),
       ],
      },
     ),
    ("graph.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ("mode", 'SET'),
       ],
      },
     ),
    ("graph.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("tweak", True),
       ("mode", 'ADD'),
       ],
      },
     ),
    ("graph.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("graph.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("graph.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("graph.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("graph.select_column",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("mode", 'KEYS'),
       ],
      },
     ),
    ("graph.select_column",
     {"type": 'K', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'CFRA'),
       ],
      },
     ),
    ("graph.select_column",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MARKERS_COLUMN'),
       ],
      },
     ),
    ("graph.select_column",
     {"type": 'K', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MARKERS_BETWEEN'),
       ],
      },
     ),
    ("graph.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("graph.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("graph.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("graph.frame_jump", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'GRAPH_MT_snap_pie'),
       ],
      },
     ),
    ("graph.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("graph.handle_type", {"type": 'V', "value": 'PRESS'}, None),
    ("graph.interpolation_type", {"type": 'T', "value": 'PRESS'}, None),
    ("graph.easing_type", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("graph.smooth", {"type": 'O', "value": 'PRESS', "alt": True}, None),
    ("graph.sample", {"type": 'O', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("graph.bake", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'GRAPH_MT_delete'),
       ],
      },
     ),
    ("graph.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("confirm", False),
       ],
      },
     ),
    ("graph.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("graph.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("graph.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("graph.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("graph.click_insert", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("graph.click_insert",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("graph.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("graph.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("graph.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'GRAPH_MT_key_smoothing'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'GRAPH_MT_key_blending'),
       ],
      },
     ),
    ("graph.previewrange_set", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("graph.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("graph.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("graph.view_selected", {"type": 'W', "value": 'PRESS'}, None),
    ("graph.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'GRAPH_MT_view_pie'),
       ],
      },
     ),
    ("graph.fmodifier_add",
     {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("only_active", False),
       ],
      },
     ),
    ("anim.channels_editable_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_fcurve'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'GRAPH_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'GRAPH_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'GRAPH_MT_pivot_pie'),
       ],
      },
     ),
    ("graph.cursor_set", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Image",
  {"space_type": 'IMAGE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("image.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("image.view_all",
     {"type": 'HOME', "value": 'PRESS', "shift": True},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("image.view_selected", {"type": 'W', "value": 'PRESS', "ctrl": True}, None),
    ("image.view_cursor_center", {"type": 'C', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("image.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("image.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("image.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("image.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("image.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("image.view_zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("image.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("image.sample", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("point", 'BLACK_POINT'),
       ],
      },
     ),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("point", 'WHITE_POINT'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'EDIT'),
       ("toggle", True),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 0),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 1),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 2),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 3),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 4),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 5),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 6),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 7),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 8),
       ],
      },
     ),
    ("image.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("image.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_pivot_pie'),
       ],
      },
     ),
    ],
   },
  ),
 ("Node Editor",
  {"space_type": 'NODE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_switch_node_type_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_copy_node_properties_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'BACK_SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_link_active_to_selected_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_add_reroutes_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_nw_add_reroutes_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_nw_node_wrangler_menu'),
       ],
      },
     ),
    ("node.nw_reset_nodes", {"type": 'BACK_SPACE', "value": 'PRESS'}, None),
    ("node.nw_align_nodes", {"type": 'EQUAL', "value": 'PRESS', "shift": True}, None),
    ("node.nw_viewer_focus", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("node.nw_lazy_connect",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("with_menu", True),
       ],
      },
     ),
    ("node.nw_lazy_connect",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("with_menu", False),
       ],
      },
     ),
    ("node.nw_lazy_mix", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.nw_reload_images", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("node.nw_preview_node",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("run_in_geometry_nodes", True),
       ],
      },
     ),
    ("node.nw_preview_node",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("run_in_geometry_nodes", False),
       ],
      },
     ),
    ("node.nw_swap_links", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("node.nw_frame_selected", {"type": 'P', "value": 'PRESS', "shift": True}, None),
    ("node.nw_del_unused", {"type": 'X', "value": 'PRESS', "alt": True}, None),
    ("node.nw_bg_reset", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.nw_add_textures_for_principled", {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.nw_add_texture", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("node.nw_select_parent_child",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("option", 'PARENT'),
       ],
      },
     ),
    ("node.nw_select_parent_child",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("option", 'CHILD'),
       ],
      },
     ),
    ("node.nw_link_out", {"type": 'O', "value": 'PRESS'}, None),
    ("node.nw_detach_outputs", {"type": 'D', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("node.nw_copy_label",
     {"type": 'V', "value": 'PRESS', "shift": True},
     {"properties":
      [("option", 'FROM_ACTIVE'),
       ],
      },
     ),
    ("node.nw_modify_labels", {"type": 'L', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("node.nw_clear_label",
     {"type": 'L', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", False),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'ZERO', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'NUMPAD_0', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 1.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("option", 0.0),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("option", 0.01),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("option", -0.01),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", 0.1),
       ],
      },
     ),
    ("node.nw_factor",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("option", -0.1),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'SEMI_COLON', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", False),
       ("use_outputs_names", True),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'SEMI_COLON', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", False),
       ("use_outputs_names", True),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'QUOTE', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", True),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'QUOTE', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", True),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ("use_node_name", False),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_link_active_to_selected",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ("use_node_name", False),
       ("use_outputs_names", False),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'UP_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'PREV'),
       ("operation", 'PREV'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'NEXT'),
       ("operation", 'NEXT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'PERIOD', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'CURRENT'),
       ("operation", 'GREATER_THAN'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'COMMA', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'CURRENT'),
       ("operation", 'LESS_THAN'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'SLASH', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'DIVIDE'),
       ("operation", 'DIVIDE'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'DIVIDE'),
       ("operation", 'DIVIDE'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'MINUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'SUBTRACT'),
       ("operation", 'SUBTRACT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'SUBTRACT'),
       ("operation", 'SUBTRACT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'EIGHT', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MULTIPLY'),
       ("operation", 'MULTIPLY'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MULTIPLY'),
       ("operation", 'MULTIPLY'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'EQUAL', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'ADD'),
       ("operation", 'ADD'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'ADD'),
       ("operation", 'ADD'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'ZERO', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MIX'),
       ("operation", 'CURRENT'),
       ],
      },
     ),
    ("node.nw_batch_change",
     {"type": 'NUMPAD_0', "value": 'PRESS', "alt": True},
     {"properties":
      [("blend_type", 'MIX'),
       ("operation", 'CURRENT'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'PERIOD', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'GREATER_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'COMMA', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'LESS_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'MIX'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ALPHAOVER'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ALPHAOVER'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'ZCOMBINE'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'GREATER_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'COMMA', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'LESS_THAN'),
       ("merge_type", 'MATH'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'SLASH', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'DIVIDE'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'SUBTRACT'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EIGHT', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MULTIPLY'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.nw_merge_nodes",
     {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'MIX'),
       ("merge_type", 'AUTO'),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ("select_passthrough", True),
       ],
      },
     ),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True}, None),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True}, None),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("node.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("node.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("tweak", False),
       ],
      },
     ),
    ("node.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("node.link",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("detach", False),
       ],
      },
     ),
    ("node.link",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("detach", True),
       ],
      },
     ),
    ("node.resize", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("node.add_reroute", {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True}, None),
    ("node.links_cut", {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True}, None),
    ("node.links_mute", {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True, "alt": True}, None),
    ("node.select_link_viewer", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.backimage_move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "repeat": True},
     {"properties":
      [("factor", 0.8333333),
       ],
      },
     ),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "alt": True, "repeat": True},
     {"properties":
      [("factor", 1.2),
       ],
      },
     ),
    ("node.backimage_fit", {"type": 'HOME', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_sample", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ],
      },
     ),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_add'),
       ],
      },
     ),
    ("node.duplicate_move",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.duplicate_move_linked",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.duplicate_move_keep_inputs",
     {"type": 'D', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("node.detach", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("node.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("node.hide_toggle", {"type": 'H', "value": 'PRESS'}, None),
    ("node.mute_toggle", {"type": 'M', "value": 'PRESS'}, None),
    ("node.preview_toggle", {"type": 'H', "value": 'PRESS', "shift": True}, None),
    ("node.hide_socket_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("node.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("node.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("node.view_selected", {"type": 'W', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_view_pie'),
       ],
      },
     ),
    ("node.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("node.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("node.delete_reconnect", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("node.delete_reconnect", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_linked_to", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("node.select_linked_from", {"type": 'L', "value": 'PRESS'}, None),
    ("node.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", False),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", True),
       ],
      },
     ),
    ("node.find_node", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_make", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_ungroup", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.group_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("exit", False),
       ],
      },
     ),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("exit", True),
       ],
      },
     ),
    ("node.read_viewlayers", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("node.render_changed", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.clipboard_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("node.clipboard_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("node.viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("node.clear_viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.translate_attach",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("node.translate_attach",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("view2d_edge_pan", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("view2d_edge_pan", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("node.move_detach_links_release",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "alt": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.move_detach_links",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "alt": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap_node'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_node_element'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Outliner",
  {"space_type": 'OUTLINER', "region_type": 'WINDOW'},
  {"items":
   [("outliner.highlight_update", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("outliner.item_rename",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("use_active", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("tweak", True),
       ("mode", 'ADD'),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.operation", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_view_pie'),
       ],
      },
     ),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True}, None),
    ("outliner.show_hierarchy", {"type": 'HOME', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'PERIOD', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'W', "value": 'PRESS'}, None),
    ("outliner.scroll_page",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", False),
       ],
      },
     ),
    ("outliner.scroll_page",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", True),
       ],
      },
     ),
    ("outliner.show_one_level", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("outliner.show_one_level",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.expanded_toggle", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("outliner.keyingset_add_selected", {"type": 'K', "value": 'PRESS'}, None),
    ("outliner.keyingset_remove_selected", {"type": 'K', "value": 'PRESS', "alt": True}, None),
    ("anim.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("outliner.collection_new", {"type": 'C', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("outliner.collection_exclude_set", {"type": 'E', "value": 'PRESS'}, None),
    ("outliner.collection_exclude_clear", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("outliner.hide", {"type": 'H', "value": 'PRESS'}, None),
    ("outliner.unhide_all", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("outliner.id_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.id_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
